                                                                        
#include "image_bits_include.h"                                         
                                                                        
                .text                                                   
                                                                        
                .balign 4                                               
                                                                        
#ifndef C_AFFICHER_CONTENU                                              
                .global  afficher_contenu                               
                                                                        
afficher_contenu:                                                       
#endif   // C_AFFICHER_CONTENU                                          
